# -*- coding: utf-8 -*-
"""PreciousCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsVdrKoG5uv-FXhqijMZNoO0rHohwggz
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

# Title and description
st.title("Building Life Cycle Prediction Model")
st.write("Enter the building parameters to predict the life cycle of the building.")

# Input fields
cement = st.number_input("Cement (kg/m³)", min_value=0.0)
slag = st.number_input("Blast Furnace Slag (kg/m³)", min_value=0.0)
fly_ash = st.number_input("Fly Ash (kg/m³)", min_value=0.0)
water = st.number_input("Water (kg/m³)", min_value=0.0)
super_plasticizer = st.number_input("Superplasticizer (kg/m³)", min_value=0.0)
coarse_agg = st.number_input("Coarse Aggregate (kg/m³)", min_value=0.0)
fine_agg = st.number_input("Fine Aggregate (kg/m³)", min_value=0.0)
age = st.number_input("Age of Testing (days)", min_value=0)

# Load your model
# Assuming you have a pre-trained model or you can train here based on your dataset
def load_model():
    data = pd.read_excel('newdataset.csv.xlsx')
    data.columns = ['Cement', 'Blast_furnace_Slag', 'Fly_Ash', 'Water', 'Super_plasticizer',
                    'Coarse_Aggregate', 'Fine_Aggregate', 'Age_of_testing', 'Compressive_Strength']
    X = data.drop('Compressive_Strength', axis=1)
    y = data['Compressive_Strength']

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    model = LinearRegression()
    model.fit(X_scaled, y)

    return model, scaler

# Predicting
model, scaler = load_model()

if st.button('Predict'):
    input_data = np.array([[cement, slag, fly_ash, water, super_plasticizer, coarse_agg, fine_agg, age]])
    input_data_scaled = scaler.transform(input_data)
    prediction = model.predict(input_data_scaled)

    st.write(f"The predicted compressive strength is: {prediction[0]:.2f} MPa")

# Commented out IPython magic to ensure Python compatibility.
# # Step 1: Create the requirements.txt file manually
# %%writefile requirements.txt
# pandas==1.5.0
# numpy>=1.20
# seaborn==0.11.2
# matplotlib
# scikit-learn
# streamlit
# 
# # Step 2: Verify the contents of requirements.txt
# !cat requirements.txt
# 
# # Step 3: Download the requirements.txt file
# from google.colab import files
# files.download('requirements.txt')
#